dbname = "friendbook"
dbuser = "root"
dbpassword = "root"
jwtkey = "secret_key"
sessionKey = "the-road-ahead"
sesEmail = "amoghpareek1@gmail.com"
serviceURL = "http://localhost:3000"
sesEndpoint = "https://email.ap-south-1.amazonaws.com"
sesAccessKeyID = "AKIAIPXDCOBJINKUOXPQ"